### PR TITLE
freedom_e: arduino: Add missing files

### PR DESCRIPTION
**Pull request by alistair23**
Add some missing files to the BSP that are required to compile the
WiFi101 library.

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>

### CODE REVIEW

**Review by palmer-dabbelt — APPROVED** [review]
I'm OK with this, but it really doesn't appear to have anything to do with our core.  Is this how Arduino stuff is supposed to be managed?

**Comment by alistair23** [comment]
As far as I could tell these have to be included. I see them in other BSPs and when trying to use the WiFi library it fails to build without these files.

**Comment by alistair23** [comment]
Ping!

**Comment by alistair23** [comment]
Ping^2

**Comment by aswaterman** [comment]
@palmer-dabbelt since you already approved this, and github won't allow me to click the button, can you do so?

**Comment by alistair23** [comment]
Ping^3

**Pull request merged**
